<?php

namespace App\Nova\Metrics;

use App\Models\Transaction;
use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Metrics\Value;

class TotalTransactions extends Value
{

    private $title;
    private $uri;
    private $field;

    public function __construct($component = null, $title = 'Ümumi ödənişlər', $uri = 'total-transactions', $field = 'price')
    {

        $this->title = $title;
        $this->uri = $uri;
        $this->field = $field;
    }

    public function calculate(NovaRequest $request)
    {
        return $this->sum($request, Transaction::class, $this->field);
    }

    /**
     * Get the ranges available for the metric.
     *
     * @return array
     */
    public function ranges()
    {
        return [
            'TODAY' => __('Today'),
            30 => __('30 Days'),
            60 => __('60 Days'),
            365 => __('365 Days'),
            'MTD' => __('Month To Date'),
            'QTD' => __('Quarter To Date'),
            'YTD' => __('Year To Date'),
        ];
    }

    public function cacheFor()
    {
        // return now()->addMinutes(5);
    }

    public function uriKey()
    {
        return $this->uri;
    }

    public function name()
    {
        return $this->title; // TODO: Change the autogenerated stub
    }
}
