<?php

namespace App\Nova;

use Eibrahimli\CalculatedField\BroadcasterField;
use Eibrahimli\CalculatedField\ListenerField;
use Eibrahimli\CalculationField\CalculationField;
use Eibrahimli\CustomFieldHelpCalculation\CustomFieldHelpCalculation;
use Eibrahimli\EdvCalculation\EdvCalculation;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class AssetInner extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\AssetInner::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    public static $displayInNavigation = false;

    public static function label(): string
    {
        return 'Qeyri maddi aktivlərin detalı'; // TODO: Change the autogenerated stub
    }

    public static function singularLabel(): string
    {
        return 'Qeyri maddi aktivlərin detalı'; // TODO: Change the autogenerated stub
    }

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            Text::make(__("Adı"),"name"),
            BelongsTo::make(__('Malların iş və xidmətlərin kateqoriyası'), 'assetCategory', AssetCategory::class)->showCreateRelationButton(),
            Text::make(__("Ölçü vahidi"),"measure"),
            CalculationField::make(__("Miqdar"),"quantity"),
            CalculationField::make(__("Qiyməti"),"unit_price"),
            CustomFieldHelpCalculation::make(__("Məbləği"),"price")->tax(false),
            Text::make(__("ƏDV"),"edv"),
            Text::make(__("Tam qiyməti"),"total_price"),
            Text::make(__("Debet"),"debet"),
            Text::make(__("Kredit"),"credit"),
            BelongsTo::make(__('Qeyri Maddi aktiv '), 'asset', MainAsset::class),

        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
