<?php

namespace App\Nova;

use App\Nova\Metrics\AssetsMetrics;
use App\Nova\Metrics\RegistryMetrics;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class Registry extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Registry::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'name';

    public static $group = 'Mühasibatlıq';

    public static function label(): string
    {
        return 'Reyestr'; // TODO: Change the autogenerated stub
    }

    public static function singularLabel(): string
    {
        return 'Reyestr'; // TODO: Change the autogenerated stub
    }

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            Text::make(__("Məbləğ"),"amount"),
            Text::make(__("Debet"),"debet"),
            Text::make(__("Kredit"),"credit"),
            Text::make(__("Əməliyyat"),"reg_type"),
            Text::make(__("Əməliyyat nömrəsi"),"reg_id"),
            Text::make(__("Xərcin tipi"),"product_id"),
            Text::make(__("Xərcin adı"),"product_name"),
            Text::make(__("Filial"),"branch_id"),
            Text::make(__("Hesab"),"account_id"),
            Text::make(__("Müştəri"),"customer_id"),
            Text::make(__("Müqavilə"),"contract_id"),
            Text::make(__("Təchizatçı"),"supplier_id"),
            Text::make(__("Tarix"),"created_at"),

        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [

            new RegistryMetrics(null,$this,"Yeni reyestr","new"),
            new RegistryMetrics(null,$this,"Toplam məbləğ","price"),
        ];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
