<?php

namespace App\Nova;

use App\Nova\Filters\ReportDateFilter;
use Illuminate\Http\Request;
use Laravel\Nova\Http\Requests\NovaRequest;
use NrmlCo\NovaBigFilter\NovaBigFilter;
use OptimistDigital\NovaInputFilter\InputFilter;

class Report extends Customer
{

    public static function indexQuery(NovaRequest $request, $query): \Illuminate\Database\Eloquent\Builder
    {
        $query->where('id', 1);
        return $query; // TODO: Change the autogenerated stub
    }


    public static function label(): string
    {
        return "Hesabatlar";
    }

    public static function singularLabel(): string
    {
        return 'Hesabat';
    }

    public function cards(Request $request): array
    {
        return [
            new NovaBigFilter(),
        ]; // TODO: Change the autogenerated stub
    }

    public function actions(Request $request): array
    {
        return parent::actions($request);
    }

    public function filters(Request $request): array
    {
        return [
            new ReportDateFilter('created_at', true, 'Tarixdən'),
            new ReportDateFilter('created_at', false, 'Tarixə'),
        ];
    }


}
